package model

// Metric 业务指标
type Metric struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Identifier  string   `json:"identifier"`
	Description string   `json:"description,omitempty"`
	Type        string   `json:"type"` // sum|count|average|ratio|formula
	Formula     string   `json:"formula,omitempty"`
	TableName   string   `json:"tableName,omitempty"`
	FieldName   string   `json:"fieldName,omitempty"`
	Format      string   `json:"format,omitempty"` // number|currency|percent|days
	Tags        []string `json:"tags,omitempty"`
	IsCore      bool     `json:"isCore,omitempty"`
}

// Dimension 维度
type Dimension struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Identifier string `json:"identifier"`
	TableName  string `json:"tableName"`
	FieldName  string `json:"fieldName"`
	DataType   string `json:"dataType"` // string|number|date|boolean
}

// Relation 表关系
type Relation struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	SourceTable string `json:"sourceTable"`
	TargetTable string `json:"targetTable"`
	SourceField string `json:"sourceField"`
	TargetField string `json:"targetField"`
	Type        string `json:"type"` // one-to-one|one-to-many|many-to-one|many-to-many
}

// SemanticModel 语义模型
type SemanticModel struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	Description     string      `json:"description,omitempty"`
	DataSourceID    string      `json:"dataSourceId"`
	Metrics         []Metric    `json:"metrics"`
	Dimensions      []Dimension `json:"dimensions"`
	Relations       []Relation  `json:"relations"`
	IsAutoGenerated bool        `json:"isAutoGenerated,omitempty"`
	CreatedAt       int64       `json:"createdAt"`
	UpdatedAt       int64       `json:"updatedAt"`
}
