export interface DashboardData {
  months: string[];
  sales: number[];
  profit: number[];
  channels: { value: number; name: string }[];
  regions: string[];
  regionSales: number[];
  totalSales: number;
  growth: number;
  customers: number;
}

export type DataSourceType =
  | "mysql"
  | "postgresql"
  | "sqlserver"
  | "oracle"
  | "mongodb"
  | "redis"
  | "elasticsearch"
  | "clickhouse"
  | "snowflake"
  | "bigquery"
  | "hive"
  | "spark"
  | "csv"
  | "excel"
  | "api"
  | "s3"
  | "kafka"
  | "other";

export interface DatabaseConnectionConfig {
  host: string;
  port: number;
  database: string;
  username: string;
  password: string;
  ssl?: boolean;
}

export interface DataSourceConfig {
  id: string;
  type: DataSourceType;
  name: string;
  description?: string;
  // 数据库连接配置（仅当 type 为 mysql/postgresql 等时使用）
  connection?: DatabaseConnectionConfig;
  // API 数据源配置
  apiConfig?: {
    url: string;
    method: "GET" | "POST";
    headers?: Record<string, string>;
    authType?: "none" | "bearer" | "basic" | "apikey";
    authToken?: string;
  };
  // 文件数据源
  fileConfig?: {
    fileName: string;
    fileSize: number;
    uploadedAt: number;
  };
  // 连接状态
  status?: "connected" | "disconnected" | "error";
  lastSyncAt?: number;
  // 数据表/集合信息（连接后自动获取）
  tables?: string[];
  // 语义层信息
  semanticModel?: SemanticModel;
}

// ============ 语义层类型定义 ============

/**
 * 指标类型
 */
export type MetricType = "sum" | "count" | "average" | "min" | "max" | "ratio" | "formula";

/**
 * 业务指标定义
 */
export interface Metric {
  id: string;
  name: string;              // 显示名称：GMV
  identifier: string;        // 英文标识：gmv
  description?: string;      // 描述：成交总额
  type: MetricType;          // 计算类型
  formula?: string;          // 计算公式：SUM(orders.amount)
  tableName?: string;        // 来源表
  fieldName?: string;        // 来源字段
  filters?: MetricFilter[];  // 过滤条件
  format?: "number" | "currency" | "percent" | "days";
  tags?: string[];           // 标签：["销售", "核心指标"]
  isCore?: boolean;          // 是否核心指标
  createdAt?: number;
  updatedAt?: number;
}

/**
 * 指标过滤条件
 */
export interface MetricFilter {
  field: string;
  operator: "=" | "!=" | ">" | "<" | ">=" | "<=" | "in" | "like";
  value: any;
}

/**
 * 维度定义
 */
export interface Dimension {
  id: string;
  name: string;              // 显示名称：地域
  identifier: string;        // 英文标识：region
  tableName: string;         // 来源表
  fieldName: string;         // 来源字段
  dataType: "string" | "number" | "date" | "boolean";
  hierarchy?: string[];      // 层次结构：['province', 'city']
  tags?: string[];
}

/**
 * 表关系定义
 */
export interface Relation {
  id: string;
  name: string;                          // 关系名称
  sourceTable: string;                   // 源表
  targetTable: string;                   // 目标表
  sourceField: string;                   // 源字段
  targetField: string;                   // 目标字段
  type: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  description?: string;
}

/**
 * 语义模型（Semantic Model）
 * ThoughtSpot SpotterModel 的简化版
 */
export interface SemanticModel {
  id: string;
  name: string;                // 模型名称
  description?: string;
  dataSourceId: string;        // 关联数据源
  metrics: Metric[];           // 指标集合
  dimensions: Dimension[];     // 维度集合
  relations: Relation[];       // 关系集合
  isAutoGenerated?: boolean;   // 是否 AI 自动生成
  createdAt: number;
  updatedAt: number;
}

export interface CompanyInfo {
  companyName: string;
  industry: string;
  size: string;
  region: string;
  businessModel: string;
  coreGoals: string;
}

export interface CompanyProfile {
  summary: string;
  analysisFocuses: string[];
  recommendedMetrics: string[];
}

export interface UserSession {
  id: string;
  name: string;
  email: string;
  createdAt: number;
  isOnboarded: boolean;
  companyInfo?: CompanyInfo;
  dataSources?: DataSourceConfig[];
  companyProfile?: CompanyProfile;
}

export interface DashboardConfig {
  id: string;
  title: string;
  templateId: string;
  createdAt: number;
  updatedAt: number;
  data: DashboardData;
  thumbnail?: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  files?: { name: string; summary?: string }[];
  timestamp: number;
  // SQL 相关
  sqlQuery?: {
    sql: string;
    executed?: boolean;
    error?: string;
    result?: any[];
  };
  // Schema 上下文
  schemaContext?: string;
}

export type DashboardTemplateId = "sales" | "operations" | "finance" | "custom";

export interface DashboardTemplate {
  id: DashboardTemplateId;
  name: string;
  description: string;
  layout: string;
}
