"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { getCurrentUser } from "@/lib/user-store";
import type { SemanticModel, Metric, Dimension } from "@/lib/types";

export default function SemanticModelPage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [semanticModel, setSemanticModel] = useState<SemanticModel | null>(null);
  const [selectedTab, setSelectedTab] = useState<"metrics" | "dimensions" | "relations">("metrics");

  useEffect(() => {
    const currentUser = getCurrentUser();
    setUser(currentUser);
    
    // 加载语义模型（从 Mock 数据或 API）
    loadSemanticModel();
  }, []);

  const loadSemanticModel = async () => {
    setLoading(true);
    
    // TODO: 调用 API 获取语义模型
    // 暂时使用 Mock 数据
    const mockModel: SemanticModel = {
      id: "sem-1",
      name: "生产数据库 - 业务语义模型",
      dataSourceId: "mock-mysql-001",
      isAutoGenerated: true,
      createdAt: Date.now() - 86400000,
      updatedAt: Date.now(),
      metrics: [
        {
          id: "metric-gmv",
          name: "GMV",
          identifier: "gmv",
          description: "成交总额",
          type: "sum",
          formula: "SUM(orders.amount)",
          tableName: "orders",
          fieldName: "amount",
          format: "currency",
          tags: ["销售", "核心指标"],
          isCore: true,
        },
        {
          id: "metric-order-count",
          name: "订单量",
          identifier: "order_count",
          description: "订单总数",
          type: "count",
          formula: "COUNT(orders.id)",
          tableName: "orders",
          fieldName: "id",
          format: "number",
          tags: ["销售", "核心指标"],
          isCore: true,
        },
        {
          id: "metric-atv",
          name: "客单价",
          identifier: "atv",
          description: "平均每个客户的消费金额",
          type: "ratio",
          formula: "SUM(orders.amount) / COUNT(DISTINCT orders.customer_id)",
          tableName: "orders",
          fieldName: "amount",
          format: "currency",
          tags: ["销售", "效率指标"],
          isCore: true,
        },
      ],
      dimensions: [
        {
          id: "dim-orders-region",
          name: "地域",
          identifier: "region",
          tableName: "orders",
          fieldName: "region",
          dataType: "string",
          tags: ["orders"],
        },
        {
          id: "dim-orders-status",
          name: "状态",
          identifier: "status",
          tableName: "orders",
          fieldName: "status",
          dataType: "string",
          tags: ["orders"],
        },
        {
          id: "dim-orders-date",
          name: "日期",
          identifier: "created_at",
          tableName: "orders",
          fieldName: "created_at",
          dataType: "date",
          tags: ["orders"],
        },
      ],
      relations: [],
    };
    
    setSemanticModel(mockModel);
    setLoading(false);
  };

  const handleRegenerate = async () => {
    if (!confirm("确定要重新生成语义模型吗？现有自定义指标可能会丢失。")) return;
    
    // TODO: 调用 API 重新生成
    alert("语义模型重新生成中...");
  };

  const handleSaveMetric = (metric: Metric) => {
    // TODO: 保存指标
    alert("指标已保存");
  };

  const handleDeleteMetric = (metricId: string) => {
    if (!confirm("确定要删除这个指标吗？")) return;
    // TODO: 删除指标
    alert("指标已删除");
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-4">
              <button
                onClick={() => router.push("/")}
                className="text-gray-600 hover:text-gray-900"
              >
                ← 返回
              </button>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">语义模型</h1>
                <p className="text-sm text-gray-500">AI 自动发现的业务指标和维度</p>
              </div>
            </div>
            <button
              onClick={handleRegenerate}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              🔄 重新生成
            </button>
          </div>
        </div>
      </div>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Tab 导航 */}
        <div className="flex gap-4 mb-6 border-b">
          <button
            onClick={() => setSelectedTab("metrics")}
            className={`px-4 py-2 font-medium ${
              selectedTab === "metrics"
                ? "border-b-2 border-blue-600 text-blue-600"
                : "text-gray-600 hover:text-gray-900"
            }`}
          >
            📊 指标 ({semanticModel?.metrics.length || 0})
          </button>
          <button
            onClick={() => setSelectedTab("dimensions")}
            className={`px-4 py-2 font-medium ${
              selectedTab === "dimensions"
                ? "border-b-2 border-blue-600 text-blue-600"
                : "text-gray-600 hover:text-gray-900"
            }`}
          >
            🧩 维度 ({semanticModel?.dimensions.length || 0})
          </button>
          <button
            onClick={() => setSelectedTab("relations")}
            className={`px-4 py-2 font-medium ${
              selectedTab === "relations"
                ? "border-b-2 border-blue-600 text-blue-600"
                : "text-gray-600 hover:text-gray-900"
            }`}
          >
            🔗 关系 ({semanticModel?.relations.length || 0})
          </button>
        </div>

        {/* 指标列表 */}
        {selectedTab === "metrics" && (
          <div className="space-y-4">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-gray-900">业务指标</h2>
              <button className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 text-sm">
                + 新增指标
              </button>
            </div>

            {semanticModel?.metrics.map((metric) => (
              <MetricCard
                key={metric.id}
                metric={metric}
                onSave={handleSaveMetric}
                onDelete={handleDeleteMetric}
              />
            ))}
          </div>
        )}

        {/* 维度列表 */}
        {selectedTab === "dimensions" && (
          <div className="bg-white rounded-lg shadow overflow-hidden">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">名称</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">标识</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">来源表</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">类型</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">标签</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {semanticModel?.dimensions.map((dim) => (
                  <tr key={dim.id}>
                    <td className="px-6 py-4 text-sm font-medium text-gray-900">{dim.name}</td>
                    <td className="px-6 py-4 text-sm text-gray-500 font-mono">{dim.identifier}</td>
                    <td className="px-6 py-4 text-sm text-gray-500">{dim.tableName}</td>
                    <td className="px-6 py-4 text-sm text-gray-500">{dim.dataType}</td>
                    <td className="px-6 py-4 text-sm text-gray-500">
                      {dim.tags?.map((tag) => (
                        <span key={tag} className="inline-block px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded mr-1">
                          {tag}
                        </span>
                      ))}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* 关系列表 */}
        {selectedTab === "relations" && (
          <div className="bg-white rounded-lg shadow p-6">
            <p className="text-gray-500">关系识别功能开发中...</p>
          </div>
        )}
      </main>
    </div>
  );
}

interface MetricCardProps {
  metric: Metric;
  onSave: (metric: Metric) => void;
  onDelete: (metricId: string) => void;
}

function MetricCard({ metric, onSave, onDelete }: MetricCardProps) {
  const [editing, setEditing] = useState(false);
  const [editedMetric, setEditedMetric] = useState(metric);

  const typeColors: Record<string, string> = {
    sum: "bg-blue-100 text-blue-800",
    count: "bg-green-100 text-green-800",
    average: "bg-purple-100 text-purple-800",
    ratio: "bg-orange-100 text-orange-800",
    formula: "bg-pink-100 text-pink-800",
  };

  const typeLabels: Record<string, string> = {
    sum: "求和",
    count: "计数",
    average: "平均",
    ratio: "比率",
    formula: "公式",
  };

  return (
    <div className="bg-white rounded-lg shadow p-4">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-2">
            <h3 className="text-lg font-semibold text-gray-900">{metric.name}</h3>
            {metric.isCore && (
              <span className="px-2 py-0.5 bg-red-100 text-red-700 text-xs rounded font-medium">
                核心指标
              </span>
            )}
            <span className={`px-2 py-0.5 text-xs rounded ${typeColors[metric.type]}`}>
              {typeLabels[metric.type]}
            </span>
          </div>

          <p className="text-sm text-gray-600 mb-2">{metric.description}</p>

          <div className="bg-gray-50 rounded p-3 font-mono text-sm text-gray-700 mb-3">
            <div className="text-xs text-gray-500 mb-1">计算公式:</div>
            {metric.formula}
          </div>

          <div className="flex items-center gap-2 text-sm text-gray-500">
            <span>📊 {metric.tableName}.{metric.fieldName}</span>
            <span>•</span>
            <span>格式：{metric.format}</span>
          </div>

          {metric.tags && metric.tags.length > 0 && (
            <div className="flex gap-1 mt-3">
              {metric.tags.map((tag) => (
                <span key={tag} className="px-2 py-0.5 bg-gray-100 text-gray-700 text-xs rounded">
                  {tag}
                </span>
              ))}
            </div>
          )}
        </div>

        <div className="flex gap-2 ml-4">
          <button
            onClick={() => setEditing(!editing)}
            className="px-3 py-1.5 text-sm bg-blue-50 text-blue-600 rounded hover:bg-blue-100"
          >
            {editing ? "取消" : "编辑"}
          </button>
          <button
            onClick={() => onDelete(metric.id)}
            className="px-3 py-1.5 text-sm bg-red-50 text-red-600 rounded hover:bg-red-100"
          >
            删除
          </button>
        </div>
      </div>
    </div>
  );
}
