package handler

import (
	"ai-bi-server/internal/model"
	"ai-bi-server/internal/service"
	"encoding/json"
	"net/http"
	"strings"
)

// DashboardHandler 大屏处理器
type DashboardHandler struct {
	service *service.DashboardService
}

// NewDashboardHandler 创建大屏处理器
func NewDashboardHandler(service *service.DashboardService) *DashboardHandler {
	return &DashboardHandler{service: service}
}

// ListDashboards 获取大屏列表
func (h *DashboardHandler) ListDashboards(w http.ResponseWriter, r *http.Request) {
	// /api/tenants/{id}/dashboards[?dataSourceId=xxx]
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 2 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]
	dataSourceID := r.URL.Query().Get("dataSourceId")

	dashboards, err := h.service.ListDashboards(tenantID, dataSourceID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(dashboards)
}

// GetDashboard 获取单个大屏
func (h *DashboardHandler) GetDashboard(w http.ResponseWriter, r *http.Request) {
	// /api/tenants/{id}/dashboards/{dashboardId}
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 3 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]
	dashboardID := parts[2]

	dashboard, err := h.service.GetDashboard(dashboardID, tenantID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(dashboard)
}

// CreateDashboard 创建大屏
func (h *DashboardHandler) CreateDashboard(w http.ResponseWriter, r *http.Request) {
	// POST /api/tenants/{id}/dashboards
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 2 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]

	var req struct {
		Name         string `json:"name"`
		DataSourceID string `json:"dataSourceId"`
		Description  string `json:"description"`
		LayoutType   string `json:"layoutType"`
		Widgets      string `json:"widgets"`
		IsAutoGen    bool   `json:"isAutoGen"`
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// 自动生成
	if req.Name == "" && req.DataSourceID != "" {
		dashboard, err := h.service.AutoGenerateDashboard(tenantID, req.DataSourceID, "AI 自动生成大屏")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(dashboard)
		return
	}

	// 手动创建（简化，实际需要完整实现）
	http.Error(w, "Not implemented", http.StatusNotImplemented)
}

// UpdateDashboard 更新大屏
func (h *DashboardHandler) UpdateDashboard(w http.ResponseWriter, r *http.Request) {
	// PUT /api/tenants/{id}/dashboards/{dashboardId}
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 3 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]
	dashboardID := parts[2]

	dashboard, err := h.service.GetDashboard(dashboardID, tenantID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	var req struct {
		Name        string `json:"name"`
		Description string `json:"description"`
		LayoutType  string `json:"layoutType"`
		Widgets     string `json:"widgets"`
		StoryOrder  string `json:"storyOrder"`
		Theme       string `json:"theme"`
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if req.Name != "" {
		dashboard.Name = req.Name
	}
	if req.Description != "" {
		dashboard.Description = req.Description
	}
	if req.LayoutType != "" {
		dashboard.LayoutType = model.DashboardLayoutType(req.LayoutType)
	}
	if req.Widgets != "" {
		dashboard.Widgets = req.Widgets
	}
	if req.StoryOrder != "" {
		dashboard.StoryOrder = req.StoryOrder
	}
	if req.Theme != "" {
		dashboard.Theme = req.Theme
	}

	if err := h.service.UpdateDashboard(dashboard); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(dashboard)
}

// DeleteDashboard 删除大屏
func (h *DashboardHandler) DeleteDashboard(w http.ResponseWriter, r *http.Request) {
	// DELETE /api/tenants/{id}/dashboards/{dashboardId}
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 3 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]
	dashboardID := parts[2]

	if err := h.service.DeleteDashboard(dashboardID, tenantID); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}

// RegenerateDashboard 重新生成大屏
func (h *DashboardHandler) RegenerateDashboard(w http.ResponseWriter, r *http.Request) {
	// POST /api/tenants/{id}/dashboards/{dashboardId}/regenerate
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 3 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]
	dashboardID := parts[2]

	dashboard, err := h.service.RegenerateDashboard(dashboardID, tenantID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(dashboard)
}

// GetDashboardPreview 获取大屏预览
func (h *DashboardHandler) GetDashboardPreview(w http.ResponseWriter, r *http.Request) {
	// GET /api/tenants/{id}/dashboards/{dashboardId}/preview
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 3 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]
	dashboardID := parts[2]

	dashboard, err := h.service.GetDashboard(dashboardID, tenantID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	preview, err := h.service.GetDashboardPreview(dashboard)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(preview)
}

// GetLayoutSuggestions 获取布局建议
func (h *DashboardHandler) GetLayoutSuggestions(w http.ResponseWriter, r *http.Request) {
	// GET /api/tenants/{id}/data-sources/{dsId}/dashboards/suggestions
	path := strings.TrimPrefix(r.URL.Path, "/api/tenants/")
	parts := strings.Split(strings.Trim(path, "/"), "/")

	if len(parts) < 5 {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	tenantID := parts[0]
	dataSourceID := parts[2]

	suggestions, err := h.service.GetLayoutSuggestions(tenantID, dataSourceID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(suggestions)
}
