package service

import (
	"ai-bi-server/internal/model"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// DashboardService 大屏服务
type DashboardService struct {
	db                *gorm.DB
	dataSourceService *DataSourceService
	aiFindingService  *AIFindingService
}

// NewDashboardService 创建大屏服务
func NewDashboardService(db *gorm.DB, dataSourceService *DataSourceService, aiFindingService *AIFindingService) *DashboardService {
	return &DashboardService{
		db:                db,
		dataSourceService: dataSourceService,
		aiFindingService:  aiFindingService,
	}
}

// AutoGenerateDashboard 自动生成大屏（基于 AI 发现）
func (s *DashboardService) AutoGenerateDashboard(tenantID, dataSourceID, name string) (*model.DashboardConfig, error) {
	// 获取数据源
	ds, err := s.dataSourceService.GetDataSource(dataSourceID, tenantID)
	if err != nil {
		return nil, fmt.Errorf("获取数据源失败：%w", err)
	}

	// 获取 AI 发现
	findings, err := s.aiFindingService.ListFindings(tenantID, dataSourceID, "")
	if err != nil {
		return nil, fmt.Errorf("获取 AI 发现失败：%w", err)
	}

	// 解析 schema
	schema, err := model.DeserializeSchemaInfo(ds.SchemaInfo)
	if err != nil {
		return nil, fmt.Errorf("解析 schema 失败：%w", err)
	}

	// 分析数据，生成组件配置
	widgets := s.generateWidgets(ds, schema, findings)

	// 序列化
	widgetsJSON, _ := json.Marshal(widgets)

	now := time.Now()

	dashboard := &model.DashboardConfig{
		ID:           uuid.New().String(),
		TenantID:     tenantID,
		DataSourceID: dataSourceID,
		Name:         name,
		Description:  "AI 自动生成的数据大屏",
		LayoutType:   model.LayoutAuto,
		Widgets:      string(widgetsJSON),
		StoryOrder:   s.generateStoryOrder(widgets),
		Theme:        "default",
		IsAutoGen:    true,
		CreatedAt:    now,
		UpdatedAt:    now,
	}

	if err := s.db.Create(dashboard).Error; err != nil {
		return nil, fmt.Errorf("创建大屏失败：%w", err)
	}

	return dashboard, nil
}

// generateWidgets 生成可视化组件
func (s *DashboardService) generateWidgets(ds *model.DataSource, schema map[string]interface{}, findings []model.AIFinding) []map[string]interface{} {
	widgets := make([]map[string]interface{}, 0)
	widgetIndex := 0

	structure, ok := schema["structure"].(map[string]interface{})
	if !ok {
		return widgets
	}

	tablesRaw, _ := schema["tables"].([]interface{})

	// 为每个重要的表生成组件
	for _, tableRaw := range tablesRaw {
		tableName, ok := tableRaw.(string)
		if !ok {
			continue
		}

		columnsRaw, _ := structure[tableName].([]interface{})

		// 统计数值列和分类列
		numericColumns := make([]string, 0)
		categoricalColumns := make([]string, 0)
		timeColumns := make([]string, 0)

		for _, colRaw := range columnsRaw {
			col, ok := colRaw.(map[string]interface{})
			if !ok {
				continue
			}

			fieldName, _ := col["field"].(string)
			dataType, _ := col["type"].(string)

			if s.isNumericType(dataType) {
				numericColumns = append(numericColumns, fieldName)
			} else if s.isCategoricalType(dataType) {
				categoricalColumns = append(categoricalColumns, fieldName)
			} else if s.isTimeType(dataType) {
				timeColumns = append(timeColumns, fieldName)
			}
		}

		// 生成指标卡组件
		for _, col := range numericColumns {
			widget := map[string]interface{}{
				"id":    fmt.Sprintf("widget_%d", widgetIndex),
				"type":  "metric_card",
				"title": fmt.Sprintf("%s - %s 总和", tableName, col),
				"query": map[string]interface{}{
					"type":        "aggregate",
					"tableName":   tableName,
					"column":      col,
					"aggregation": "SUM",
				},
				"config": map[string]interface{}{
					"format": "number",
					"prefix": "",
					"suffix": "",
				},
				"layout": map[string]interface{}{
					"x":      0,
					"y":      widgetIndex * 2,
					"width":  3,
					"height": 2,
				},
				"priority": s.getColumnPriority(tableName, col, findings),
			}
			widgets = append(widgets, widget)
			widgetIndex++
		}

		// 如果有分类列和数值列，生成分组柱状图
		if len(categoricalColumns) > 0 && len(numericColumns) > 0 {
			for _, catCol := range categoricalColumns {
				for _, numCol := range numericColumns {
					widget := map[string]interface{}{
						"id":    fmt.Sprintf("widget_%d", widgetIndex),
						"type":  "bar_chart",
						"title": fmt.Sprintf("%s 按 %s 分组", numCol, catCol),
						"query": map[string]interface{}{
							"type":        "group_by",
							"tableName":   tableName,
							"groupColumn": catCol,
							"valueColumn": numCol,
							"aggregation": "SUM",
							"limit":       10,
						},
						"config": map[string]interface{}{
							"orientation": "vertical",
							"showLegend":  true,
							"colorScheme": "default",
						},
						"layout": map[string]interface{}{
							"x":      (widgetIndex % 4) * 3,
							"y":      (widgetIndex / 4) * 4,
							"width":  6,
							"height": 4,
						},
						"priority": s.getColumnPriority(tableName, numCol, findings),
					}
					widgets = append(widgets, widget)
					widgetIndex++
				}
			}
		}

		// 如果有时间列和数值列，生成趋势图
		if len(timeColumns) > 0 && len(numericColumns) > 0 {
			for _, timeCol := range timeColumns {
				for _, numCol := range numericColumns {
					widget := map[string]interface{}{
						"id":    fmt.Sprintf("widget_%d", widgetIndex),
						"type":  "line_chart",
						"title": fmt.Sprintf("%s 趋势 (%s)", numCol, timeCol),
						"query": map[string]interface{}{
							"type":        "time_series",
							"tableName":   tableName,
							"timeColumn":  timeCol,
							"valueColumn": numCol,
							"aggregation": "SUM",
							"interval":    "day",
						},
						"config": map[string]interface{}{
							"showPoints":  false,
							"smooth":      true,
							"showLegend":  true,
							"colorScheme": "default",
						},
						"layout": map[string]interface{}{
							"x":      (widgetIndex % 4) * 6,
							"y":      (widgetIndex / 4) * 5,
							"width":  12,
							"height": 5,
						},
						"priority": s.getColumnPriority(tableName, numCol, findings),
					}
					widgets = append(widgets, widget)
					widgetIndex++
				}
			}
		}

		// 生成数据质量警告组件
		tableFindings := s.getTableFindings(findings, tableName)
		if len(tableFindings) > 0 {
			widget := map[string]interface{}{
				"id":    fmt.Sprintf("widget_%d", widgetIndex),
				"type":  "alert_list",
				"title": fmt.Sprintf("%s - 数据质量洞察", tableName),
				"query": map[string]interface{}{
					"type":      "findings",
					"tableName": tableName,
				},
				"config": map[string]interface{}{
					"maxItems":     5,
					"showSeverity": true,
				},
				"layout": map[string]interface{}{
					"x":      0,
					"y":      (widgetIndex / 4) * 3,
					"width":  6,
					"height": 3,
				},
				"priority": 100, // 高优先级
			}
			widgets = append(widgets, widget)
			widgetIndex++
		}
	}

	// 按优先级排序
	sort.Slice(widgets, func(i, j int) bool {
		priorityI, _ := widgets[i]["priority"].(int)
		priorityJ, _ := widgets[j]["priority"].(int)
		return priorityI > priorityJ
	})

	// 只保留前 20 个组件
	if len(widgets) > 20 {
		widgets = widgets[:20]
	}

	return widgets
}

// generateLayout 生成布局（简化版网格布局）
func (s *DashboardService) generateLayout(widgets []map[string]interface{}, findings []model.AIFinding) model.DashboardLayoutType {
	// 根据发现的数量决定布局类型
	if len(findings) > 10 {
		return model.LayoutStory // 故事线布局
	}
	return model.LayoutGrid
}

// generateStoryOrder 生成故事线顺序
func (s *DashboardService) generateStoryOrder(widgets []map[string]interface{}) string {
	// 按优先级排序组件 ID
	type widgetOrder struct {
		ID       string
		Priority int
	}

	orders := make([]widgetOrder, 0)
	for _, w := range widgets {
		id, _ := w["id"].(string)
		priority, _ := w["priority"].(int)
		orders = append(orders, widgetOrder{ID: id, Priority: priority})
	}

	sort.Slice(orders, func(i, j int) bool {
		return orders[i].Priority > orders[j].Priority
	})

	ids := make([]string, len(orders))
	for i, o := range orders {
		ids[i] = o.ID
	}

	jsonData, _ := json.Marshal(ids)
	return string(jsonData)
}

// getTableFindings 获取表的发现
func (s *DashboardService) getTableFindings(findings []model.AIFinding, tableName string) []model.AIFinding {
	result := make([]model.AIFinding, 0)
	for _, f := range findings {
		if f.TableName == tableName {
			result = append(result, f)
		}
	}
	return result
}

// getColumnPriority 获取列的优先级（基于 AI 发现）
func (s *DashboardService) getColumnPriority(tableName, columnName string, findings []model.AIFinding) int {
	priority := 50

	for _, f := range findings {
		if f.TableName == tableName && f.ColumnName == columnName {
			switch f.Severity {
			case model.AIFindingSeverityHigh:
				priority += 40
			case model.AIFindingSeverityMedium:
				priority += 20
			case model.AIFindingSeverityLow:
				priority += 10
			case model.AIFindingSeverityInfo:
				priority += 5
			}
		}
	}

	return priority
}

// 辅助函数
func (s *DashboardService) isNumericType(dataType string) bool {
	numericTypes := []string{"int", "integer", "bigint", "smallint", "tinyint", "float", "double", "decimal", "numeric", "real"}
	dataTypeLower := strings.ToLower(dataType)
	for _, t := range numericTypes {
		if strings.Contains(dataTypeLower, t) {
			return true
		}
	}
	return false
}

func (s *DashboardService) isTimeType(dataType string) bool {
	timeTypes := []string{"date", "time", "timestamp", "datetime"}
	dataTypeLower := strings.ToLower(dataType)
	for _, t := range timeTypes {
		if strings.Contains(dataTypeLower, t) {
			return true
		}
	}
	return false
}

func (s *DashboardService) isCategoricalType(dataType string) bool {
	catTypes := []string{"varchar", "char", "text", "string", "enum"}
	dataTypeLower := strings.ToLower(dataType)
	for _, t := range catTypes {
		if strings.Contains(dataTypeLower, t) {
			return true
		}
	}
	return false
}

// ListDashboards 获取大屏列表
func (s *DashboardService) ListDashboards(tenantID, dataSourceID string) ([]model.DashboardConfig, error) {
	var dashboards []model.DashboardConfig
	query := s.db.Where("tenant_id = ? AND deleted_at IS NULL", tenantID)

	if dataSourceID != "" {
		query = query.Where("data_source_id = ?", dataSourceID)
	}

	err := query.Order("created_at DESC").Find(&dashboards).Error
	return dashboards, err
}

// GetDashboard 获取单个大屏
func (s *DashboardService) GetDashboard(id, tenantID string) (*model.DashboardConfig, error) {
	var dashboard model.DashboardConfig
	err := s.db.Where("id = ? AND tenant_id = ? AND deleted_at IS NULL", id, tenantID).
		First(&dashboard).Error
	if err != nil {
		return nil, err
	}
	return &dashboard, nil
}

// UpdateDashboard 更新大屏
func (s *DashboardService) UpdateDashboard(dashboard *model.DashboardConfig) error {
	dashboard.UpdatedAt = time.Now()
	return s.db.Save(dashboard).Error
}

// DeleteDashboard 删除大屏
func (s *DashboardService) DeleteDashboard(id, tenantID string) error {
	return s.db.Where("id = ? AND tenant_id = ?", id, tenantID).
		Delete(&model.DashboardConfig{}).Error
}

// RegenerateDashboard 重新生成大屏
func (s *DashboardService) RegenerateDashboard(id, tenantID string) (*model.DashboardConfig, error) {
	// 获取现有大屏
	dashboard, err := s.GetDashboard(id, tenantID)
	if err != nil {
		return nil, err
	}

	// 删除旧组件（保留配置）
	if err := s.db.Where("id = ?", id).Delete(&model.DashboardConfig{}).Error; err != nil {
		return nil, err
	}

	// 重新生成
	return s.AutoGenerateDashboard(tenantID, dashboard.DataSourceID, dashboard.Name)
}

// GetDashboardPreview 获取大屏预览数据
func (s *DashboardService) GetDashboardPreview(dashboard *model.DashboardConfig) (map[string]interface{}, error) {
	preview := make(map[string]interface{})

	// 解析组件
	var widgets []map[string]interface{}
	if err := json.Unmarshal([]byte(dashboard.Widgets), &widgets); err != nil {
		return nil, err
	}

	// 获取数据源
	ds, err := s.dataSourceService.GetDataSource(dashboard.TenantID, dashboard.DataSourceID)
	if err != nil {
		return nil, err
	}

	// 执行每个组件的查询
	widgetData := make([]map[string]interface{}, 0)
	for _, widget := range widgets {
		query, ok := widget["query"].(map[string]interface{})
		if !ok {
			continue
		}

		data, err := s.executeQuery(ds, query)
		if err != nil {
			continue
		}

		widgetData = append(widgetData, map[string]interface{}{
			"widgetId": widget["id"],
			"data":     data,
		})
	}

	preview["widgets"] = widgetData
	return preview, nil
}

// executeQuery 执行组件查询
func (s *DashboardService) executeQuery(ds *model.DataSource, query map[string]interface{}) ([]map[string]interface{}, error) {
	queryType, _ := query["type"].(string)
	tableName, _ := query["tableName"].(string)

	switch queryType {
	case "aggregate":
		column, _ := query["column"].(string)
		aggregation, _ := query["aggregation"].(string)
		sql := fmt.Sprintf("SELECT %s(%s) as value FROM %s", aggregation, column, tableName)
		return s.dataSourceService.ExecuteQuery(ds, sql)

	case "group_by":
		groupColumn, _ := query["groupColumn"].(string)
		valueColumn, _ := query["valueColumn"].(string)
		aggregation, _ := query["aggregation"].(string)
		limit, _ := query["limit"].(float64)
		if limit == 0 {
			limit = 10
		}
		sql := fmt.Sprintf("SELECT %s, %s(%s) as value FROM %s GROUP BY %s ORDER BY value DESC LIMIT %.0f",
			groupColumn, aggregation, valueColumn, tableName, groupColumn, limit)
		return s.dataSourceService.ExecuteQuery(ds, sql)

	case "time_series":
		timeColumn, _ := query["timeColumn"].(string)
		valueColumn, _ := query["valueColumn"].(string)
		aggregation, _ := query["aggregation"].(string)
		sql := fmt.Sprintf("SELECT %s, %s(%s) as value FROM %s GROUP BY %s ORDER BY %s",
			timeColumn, aggregation, valueColumn, tableName, timeColumn, timeColumn)
		return s.dataSourceService.ExecuteQuery(ds, sql)

	case "findings":
		// 返回 AI 发现数据
		findings, err := s.aiFindingService.ListFindings(ds.TenantID, ds.ID, "")
		if err != nil {
			return nil, err
		}

		result := make([]map[string]interface{}, 0)
		for _, f := range findings {
			result = append(result, map[string]interface{}{
				"title":       f.Title,
				"description": f.Description,
				"severity":    f.Severity,
				"type":        f.Type,
			})
		}
		return result, nil

	default:
		return nil, fmt.Errorf("未知查询类型：%s", queryType)
	}
}

// GetLayoutSuggestions 获取布局建议
func (s *DashboardService) GetLayoutSuggestions(tenantID, dataSourceID string) (map[string]interface{}, error) {
	// 获取 AI 发现
	findings, err := s.aiFindingService.ListFindings(tenantID, dataSourceID, "")
	if err != nil {
		return nil, err
	}

	// 根据发现数量推荐布局
	suggestions := map[string]interface{}{
		"recommendedLayout": "grid",
		"widgetCount":       int(math.Min(float64(len(findings))*2, 20)),
		"storyMode":         len(findings) > 5,
	}

	if len(findings) > 10 {
		suggestions["recommendedLayout"] = "story"
		suggestions["reason"] = "发现较多，建议使用故事线布局引导用户关注重点"
	} else if len(findings) > 5 {
		suggestions["recommendedLayout"] = "grid"
		suggestions["reason"] = "发现适中，建议使用网格布局平衡展示"
	} else {
		suggestions["recommendedLayout"] = "free"
		suggestions["reason"] = "发现较少，建议使用自由布局灵活安排"
	}

	return suggestions, nil
}
