package service

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"ai-bi-server/internal/model"
)

// SemanticModelService 语义模型服务
type SemanticModelService struct {
	dataSourceService *DataSourceService
}

// NewSemanticModelService 创建语义模型服务
func NewSemanticModelService(dataSourceService *DataSourceService) *SemanticModelService {
	return &SemanticModelService{dataSourceService: dataSourceService}
}

// GetSemanticModel 获取数据源的语义模型
func (s *SemanticModelService) GetSemanticModel(dataSourceID string) (*model.DataSource, *SemanticModel, error) {
	// TODO: 从数据库或缓存获取
	return nil, nil, nil
}

// AutoDiscoverMetrics AI 自动发现业务指标
func (s *SemanticModelService) AutoDiscoverMetrics(ds *model.DataSource) (*SemanticModel, error) {
	if ds.SchemaInfo == "" {
		return nil, fmt.Errorf("暂无 Schema 信息，无法自动发现指标")
	}

	// 解析 Schema 信息
	var schema map[string]interface{}
	if err := json.Unmarshal([]byte(ds.SchemaInfo), &schema); err != nil {
		return nil, err
	}

	semModel := &SemanticModel{
		ID:              "sem-" + ds.ID,
		Name:            ds.Name + " - 业务语义模型",
		DataSourceID:    ds.ID,
		IsAutoGenerated: true,
		CreatedAt:       time.Now().Unix(),
		UpdatedAt:       time.Now().Unix(),
	}

	// 1. 自动识别表类型
	tableTypes := s.identifyTableTypes(schema)

	// 2. 基于表类型生成指标
	semModel.Metrics = s.generateMetrics(schema, tableTypes)

	// 3. 基于表结构生成维度
	semModel.Dimensions = s.generateDimensions(schema)

	// 4. 识别表关系
	semModel.Relations = s.identifyRelations(schema, tableTypes)

	return semModel, nil
}

// identifyTableTypes 识别表类型（订单表、用户表、商品表等）
func (s *SemanticModelService) identifyTableTypes(schema map[string]interface{}) map[string]string {
	tableTypes := make(map[string]string)

	tables, _ := schema["tables"].([]interface{})
	structure, _ := schema["structure"].(map[string]interface{})

	for _, t := range tables {
		tableName := t.(string)
		tableLower := strings.ToLower(tableName)

		// 基于表名关键词识别
		if strings.Contains(tableLower, "order") {
			tableTypes[tableName] = "orders"
		} else if strings.Contains(tableLower, "user") || strings.Contains(tableLower, "customer") {
			tableTypes[tableName] = "users"
		} else if strings.Contains(tableLower, "product") || strings.Contains(tableLower, "item") {
			tableTypes[tableName] = "products"
		} else if strings.Contains(tableLower, "category") {
			tableTypes[tableName] = "categories"
		} else if strings.Contains(tableLower, "region") || strings.Contains(tableLower, "area") {
			tableTypes[tableName] = "regions"
		} else if strings.Contains(tableLower, "date") || strings.Contains(tableLower, "time") {
			tableTypes[tableName] = "date_dim"
		} else {
			tableTypes[tableName] = "other"
		}
	}

	return tableTypes
}

// generateMetrics 生成业务指标
func (s *SemanticModelService) generateMetrics(schema map[string]interface{}, tableTypes map[string]string) []Metric {
	metrics := []Metric{}
	structure, _ := schema["structure"].(map[string]interface{})

	// 为订单表生成指标
	for tableName, tableType := range tableTypes {
		if tableType == "orders" {
			cols, _ := structure[tableName].([]interface{})
			fieldNames := s.extractFieldNames(cols)

			// GMV
			if s.hasField(fieldNames, []string{"amount", "total", "price", "gmv"}) {
				metrics = append(metrics, Metric{
					ID:          "metric-gmv",
					Name:        "GMV",
					Identifier:  "gmv",
					Description: "成交总额",
					Type:        "sum",
					Formula:     fmt.Sprintf("SUM(%s.amount)", tableName),
					TableName:   tableName,
					FieldName:   s.findField(fieldNames, []string{"amount", "total", "price", "gmv"}),
					Format:      "currency",
					Tags:        []string{"销售", "核心指标"},
					IsCore:      true,
				})
			}

			// 订单量
			metrics = append(metrics, Metric{
				ID:          "metric-order-count",
				Name:        "订单量",
				Identifier:  "order_count",
				Description: "订单总数",
				Type:        "count",
				Formula:     fmt.Sprintf("COUNT(%s.id)", tableName),
				TableName:   tableName,
				FieldName:   "id",
				Format:      "number",
				Tags:        []string{"销售", "核心指标"},
				IsCore:      true,
			})

			// 客单价
			if s.hasField(fieldNames, []string{"customer_id", "user_id", "buyer_id"}) {
				metrics = append(metrics, Metric{
					ID:          "metric-atv",
					Name:        "客单价",
					Identifier:  "atv",
					Description: "平均每个客户的消费金额",
					Type:        "ratio",
					Formula:     fmt.Sprintf("SUM(%s.amount) / COUNT(DISTINCT %s.customer_id)", tableName, tableName),
					TableName:   tableName,
					FieldName:   "amount",
					Format:      "currency",
					Tags:        []string{"销售", "效率指标"},
					IsCore:      true,
				})
			}

			// 支付金额
			if s.hasField(fieldNames, []string{"paid_amount", "payment_amount"}) {
				metrics = append(metrics, Metric{
					ID:          "metric-revenue",
					Name:        "支付金额",
					Identifier:  "revenue",
					Description: "实际支付金额",
					Type:        "sum",
					Formula:     fmt.Sprintf("SUM(%s.paid_amount)", tableName),
					TableName:   tableName,
					FieldName:   "paid_amount",
					Format:      "currency",
					Tags:        []string{"销售", "核心指标"},
					IsCore:      true,
				})
			}
		}
	}

	// 如果没有任何指标，生成通用指标
	if len(metrics) == 0 {
		metrics = append(metrics, Metric{
			ID:          "metric-record-count",
			Name:        "记录数",
			Identifier:  "record_count",
			Description: "总记录数",
			Type:        "count",
			Formula:     "COUNT(*)",
			Format:      "number",
			Tags:        []string{"基础指标"},
			IsCore:      false,
		})
	}

	return metrics
}

// generateDimensions 生成维度
func (s *SemanticModelService) generateDimensions(schema map[string]interface{}) []Dimension {
	dimensions := []Dimension{}
	structure, _ := schema["structure"].(map[string]interface{})
	tables, _ := schema["tables"].([]interface{})

	for _, t := range tables {
		tableName := t.(string)
		cols, _ := structure[tableName].([]interface{})

		for _, col := range cols {
			colMap, _ := col.(map[string]interface{})
			fieldName, _ := colMap["field"].(string)
			dataType, _ := colMap["type"].(string)

			// 识别维度字段
			if s.isDimensionField(fieldName, dataType) {
				dimensions = append(dimensions, Dimension{
					ID:         fmt.Sprintf("dim-%s-%s", tableName, fieldName),
					Name:       s.fieldToChinese(fieldName),
					Identifier: fieldName,
					TableName:  tableName,
					FieldName:  fieldName,
					DataType:   s.mapDataType(dataType),
					Tags:       []string{tableName},
				})
			}
		}
	}

	return dimensions
}

// identifyRelations 识别表关系
func (s *SemanticModelService) identifyRelations(schema map[string]interface{}, tableTypes map[string]string) []Relation {
	relations := []Relation{}
	structure, _ := schema["structure"].(map[string]interface{})

	// 简单的关系识别：查找外键
	for tableName1, cols1 := range structure {
		cols1List, _ := cols1.([]interface{})
		for _, col := range cols1List {
			colMap, _ := col.(map[string]interface{})
			fieldName, _ := colMap["field"].(string)

			// 查找可能的 FK
			if strings.HasSuffix(fieldName, "_id") && fieldName != "id" {
				// 猜测关联的表
				referencedTable := strings.TrimSuffix(fieldName, "_id") + "s"

				// 检查目标表是否存在
				for tableName2 := range structure {
					if tableName2 == referencedTable ||
						strings.Contains(strings.ToLower(tableName2), strings.ToLower(strings.TrimSuffix(fieldName, "_id"))) {
						relations = append(relations, Relation{
							ID:          fmt.Sprintf("rel-%s-%s", tableName1, tableName2),
							Name:        fmt.Sprintf("%s → %s", tableName1, tableName2),
							SourceTable: tableName1,
							TargetTable: tableName2,
							SourceField: fieldName,
							TargetField: "id",
							Type:        "many-to-one",
						})
					}
				}
			}
		}
	}

	return relations
}

// 辅助函数

func (s *SemanticModelService) extractFieldNames(cols []interface{}) []string {
	fields := []string{}
	for _, col := range cols {
		colMap, _ := col.(map[string]interface{})
		if field, ok := colMap["field"].(string); ok {
			fields = append(fields, field)
		}
	}
	return fields
}

func (s *SemanticModelService) hasField(fields []string, keywords []string) string {
	for _, field := range fields {
		fieldLower := strings.ToLower(field)
		for _, kw := range keywords {
			if strings.Contains(fieldLower, kw) {
				return field
			}
		}
	}
	return ""
}

func (s *SemanticModelService) findField(fields []string, keywords []string) string {
	return s.hasField(fields, keywords)
}

func (s *SemanticModelService) isDimensionField(fieldName, dataType string) bool {
	fieldLower := strings.ToLower(fieldName)

	// 跳过主键和数值型字段
	if fieldLower == "id" || strings.HasSuffix(fieldLower, "_id") {
		return false
	}

	// 跳过纯数值字段（这些通常是指标）
	if strings.Contains(dataType, "int") || strings.Contains(dataType, "decimal") || strings.Contains(dataType, "double") {
		return false
	}

	// 这些是典型的维度字段
	dimensionKeywords := []string{"name", "type", "category", "region", "status", "level", "date", "time", "year", "month"}
	for _, kw := range dimensionKeywords {
		if strings.Contains(fieldLower, kw) {
			return true
		}
	}

	// 字符串类型通常是维度
	if strings.Contains(dataType, "char") || strings.Contains(dataType, "text") || strings.Contains(dataType, "varchar") {
		return true
	}

	return false
}

func (s *SemanticModelService) mapDataType(dbType string) string {
	dbTypeLower := strings.ToLower(dbType)
	if strings.Contains(dbTypeLower, "int") || strings.Contains(dbTypeLower, "numeric") {
		return "number"
	}
	if strings.Contains(dbTypeLower, "date") || strings.Contains(dbTypeLower, "time") {
		return "date"
	}
	if strings.Contains(dbTypeLower, "bool") {
		return "boolean"
	}
	return "string"
}

func (s *SemanticModelService) fieldToChinese(fieldName string) string {
	// 简单的字段名转中文映射
	mapping := map[string]string{
		"province":   "省份",
		"city":       "城市",
		"region":     "区域",
		"category":   "品类",
		"status":     "状态",
		"type":       "类型",
		"level":      "等级",
		"year":       "年",
		"month":      "月",
		"day":        "日",
		"date":       "日期",
		"created_at": "创建时间",
		"updated_at": "更新时间",
	}

	if cn, ok := mapping[fieldName]; ok {
		return cn
	}

	// 默认返回英文
	return fieldName
}

// SaveSemanticModel 保存语义模型
func (s *SemanticModelService) SaveSemanticModel(model *SemanticModel) error {
	// TODO: 保存到数据库
	return nil
}

// UpdateMetric 更新指标定义
func (s *SemanticModelService) UpdateMetric(modelID string, metric Metric) error {
	// TODO: 更新指标
	return nil
}

// DeleteMetric 删除指标
func (s *SemanticModelService) DeleteMetric(modelID string, metricID string) error {
	// TODO: 删除指标
	return nil
}
