package service

import (
	"ai-bi-server/internal/model"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// SemanticModelService 语义模型服务
type SemanticModelService struct {
	db                *gorm.DB
	dataSourceService *DataSourceService
}

// NewSemanticModelService 创建语义模型服务
func NewSemanticModelService(db *gorm.DB, dataSourceService *DataSourceService) *SemanticModelService {
	return &SemanticModelService{
		db:                db,
		dataSourceService: dataSourceService,
	}
}

// BuildSemanticCache 构建语义模型缓存（用于 AI 对话增强）
func (s *SemanticModelService) BuildSemanticCache(tenantID, dataSourceID string) error {
	// 获取数据源
	ds, err := s.dataSourceService.GetDataSource(dataSourceID, tenantID)
	if err != nil {
		return fmt.Errorf("获取数据源失败：%w", err)
	}

	// 解析 schema
	if ds.SchemaInfo == "" {
		return fmt.Errorf("数据源暂无 schema 信息")
	}

	schema, err := model.DeserializeSchemaInfo(ds.SchemaInfo)
	if err != nil {
		return fmt.Errorf("解析 schema 失败：%w", err)
	}

	// 分析表结构，自动生成指标和维度
	metrics := s.autoGenerateMetrics(ds, schema)
	dimensions := s.autoGenerateDimensions(ds, schema)
	relations := s.autoGenerateRelations(ds, schema)
	nlQueries := s.generateNLQueryPatterns(ds, schema)

	// 序列化
	metricsJSON, _ := json.Marshal(metrics)
	dimensionsJSON, _ := json.Marshal(dimensions)
	relationsJSON, _ := json.Marshal(relations)
	nlQueriesJSON, _ := json.Marshal(nlQueries)

	// 检查是否存在缓存
	var cache model.SemanticModelCache
	err = s.db.Where("tenant_id = ? AND data_source_id = ?", tenantID, dataSourceID).
		First(&cache).Error

	now := time.Now()

	if err == gorm.ErrRecordNotFound {
		// 创建新缓存
		cache = model.SemanticModelCache{
			ID:           uuid.New().String(),
			TenantID:     tenantID,
			DataSourceID: dataSourceID,
			Metrics:      string(metricsJSON),
			Dimensions:   string(dimensionsJSON),
			Relations:    string(relationsJSON),
			NLQueries:    string(nlQueriesJSON),
			LastBuiltAt:  now,
			CreatedAt:    now,
			UpdatedAt:    now,
		}
		if err := s.db.Create(&cache).Error; err != nil {
			return fmt.Errorf("创建语义缓存失败：%w", err)
		}
	} else if err != nil {
		return fmt.Errorf("查询语义缓存失败：%w", err)
	} else {
		// 更新现有缓存
		cache.Metrics = string(metricsJSON)
		cache.Dimensions = string(dimensionsJSON)
		cache.Relations = string(relationsJSON)
		cache.NLQueries = string(nlQueriesJSON)
		cache.LastBuiltAt = now
		cache.UpdatedAt = now
		if err := s.db.Save(&cache).Error; err != nil {
			return fmt.Errorf("更新语义缓存失败：%w", err)
		}
	}

	return nil
}

// autoGenerateMetrics 自动生成指标定义
func (s *SemanticModelService) autoGenerateMetrics(ds *model.DataSource, schema map[string]interface{}) []map[string]interface{} {
	metrics := make([]map[string]interface{}, 0)

	structure, ok := schema["structure"].(map[string]interface{})
	if !ok {
		return metrics
	}

	tablesRaw, _ := schema["tables"].([]interface{})

	for _, tableRaw := range tablesRaw {
		tableName, ok := tableRaw.(string)
		if !ok {
			continue
		}

		columnsRaw, _ := structure[tableName].([]interface{})
		for _, colRaw := range columnsRaw {
			col, ok := colRaw.(map[string]interface{})
			if !ok {
				continue
			}

			fieldName, _ := col["field"].(string)
			dataType, _ := col["type"].(string)

			// 检测数值字段，自动生成聚合指标
			if s.isNumericType(dataType) {
				metric := map[string]interface{}{
					"name":        fmt.Sprintf("%s_%s_total", tableName, fieldName),
					"label":       fmt.Sprintf("%s%s 总和", tableName, fieldName),
					"description": fmt.Sprintf("%s 表中 %s 字段的总和", tableName, fieldName),
					"tableName":   tableName,
					"columnName":  fieldName,
					"aggregation": "SUM",
					"dataType":    "numeric",
				}
				metrics = append(metrics, metric)

				// 添加平均值指标
				metricAvg := map[string]interface{}{
					"name":        fmt.Sprintf("%s_%s_avg", tableName, fieldName),
					"label":       fmt.Sprintf("%s%s 平均值", tableName, fieldName),
					"description": fmt.Sprintf("%s 表中 %s 字段的平均值", tableName, fieldName),
					"tableName":   tableName,
					"columnName":  fieldName,
					"aggregation": "AVG",
					"dataType":    "numeric",
				}
				metrics = append(metrics, metricAvg)

				// 添加计数指标
				metricCount := map[string]interface{}{
					"name":        fmt.Sprintf("%s_count", tableName),
					"label":       fmt.Sprintf("%s 记录数", tableName),
					"description": fmt.Sprintf("%s 表的记录总数", tableName),
					"tableName":   tableName,
					"columnName":  "*",
					"aggregation": "COUNT",
					"dataType":    "integer",
				}
				metrics = append(metrics, metricCount)
			}
		}
	}

	return metrics
}

// autoGenerateDimensions 自动生成维度定义
func (s *SemanticModelService) autoGenerateDimensions(ds *model.DataSource, schema map[string]interface{}) []map[string]interface{} {
	dimensions := make([]map[string]interface{}, 0)

	structure, ok := schema["structure"].(map[string]interface{})
	if !ok {
		return dimensions
	}

	tablesRaw, _ := schema["tables"].([]interface{})

	for _, tableRaw := range tablesRaw {
		tableName, ok := tableRaw.(string)
		if !ok {
			continue
		}

		columnsRaw, _ := structure[tableName].([]interface{})
		for _, colRaw := range columnsRaw {
			col, ok := colRaw.(map[string]interface{})
			if !ok {
				continue
			}

			fieldName, _ := col["field"].(string)
			dataType, _ := col["type"].(string)

			// 检测字符串类型（可能是分类维度）
			if s.isCategoricalType(dataType) {
				dimension := map[string]interface{}{
					"name":        fmt.Sprintf("%s_%s", tableName, fieldName),
					"label":       fmt.Sprintf("%s%s", tableName, fieldName),
					"description": fmt.Sprintf("%s 表中 %s 字段的分类维度", tableName, fieldName),
					"tableName":   tableName,
					"columnName":  fieldName,
					"dataType":    "categorical",
				}
				dimensions = append(dimensions, dimension)
			}

			// 检测时间类型
			if s.isTimeType(dataType) {
				dimension := map[string]interface{}{
					"name":        fmt.Sprintf("%s_%s_date", tableName, fieldName),
					"label":       fmt.Sprintf("%s%s 日期", tableName, fieldName),
					"description": fmt.Sprintf("%s 表中 %s 字段的时间维度", tableName, fieldName),
					"tableName":   tableName,
					"columnName":  fieldName,
					"dataType":    "temporal",
					"hierarchies": []string{"year", "quarter", "month", "day"},
				}
				dimensions = append(dimensions, dimension)
			}
		}
	}

	return dimensions
}

// autoGenerateRelations 自动生成表关系定义
func (s *SemanticModelService) autoGenerateRelations(ds *model.DataSource, schema map[string]interface{}) []map[string]interface{} {
	relations := make([]map[string]interface{}, 0)

	structure, ok := schema["structure"].(map[string]interface{})
	if !ok {
		return relations
	}

	tablesRaw, _ := schema["tables"].([]interface{})
	tables := make([]string, 0)
	for _, t := range tablesRaw {
		if name, ok := t.(string); ok {
			tables = append(tables, name)
		}
	}

	// 简单检测：通过列名推测关系（实际应用中需要更复杂的检测）
	for _, tableName := range tables {
		columnsRaw, _ := structure[tableName].([]interface{})
		for _, colRaw := range columnsRaw {
			col, ok := colRaw.(map[string]interface{})
			if !ok {
				continue
			}

			fieldName, _ := col["field"].(string)

			// 检测外键（以 _id 结尾的列）
			if strings.HasSuffix(fieldName, "_id") && fieldName != "id" {
				// 推测关联表名
				refTable := strings.TrimSuffix(fieldName, "_id")

				// 检查是否存在对应的表
				for _, t := range tables {
					if t == refTable || strings.HasSuffix(t, "_"+refTable) || strings.HasSuffix(t, refTable+"s") {
						relation := map[string]interface{}{
							"name":       fmt.Sprintf("%s_to_%s", tableName, refTable),
							"fromTable":  tableName,
							"fromColumn": fieldName,
							"toTable":    refTable,
							"toColumn":   "id",
							"type":       "many_to_one",
						}
						relations = append(relations, relation)
						break
					}
				}
			}
		}
	}

	return relations
}

// generateNLQueryPatterns 生成自然语言查询模式
func (s *SemanticModelService) generateNLQueryPatterns(ds *model.DataSource, schema map[string]interface{}) []map[string]interface{} {
	queries := make([]map[string]interface{}, 0)

	structure, ok := schema["structure"].(map[string]interface{})
	if !ok {
		return queries
	}

	tablesRaw, _ := schema["tables"].([]interface{})

	for _, tableRaw := range tablesRaw {
		tableName, ok := tableRaw.(string)
		if !ok {
			continue
		}

		// 为每个表生成常见查询模式
		queries = append(queries,
			map[string]interface{}{
				"pattern":     fmt.Sprintf("%s 总数是多少", tableName),
				"intent":      "count",
				"tableName":   tableName,
				"sqlTemplate": fmt.Sprintf("SELECT COUNT(*) FROM %s", tableName),
			},
			map[string]interface{}{
				"pattern":     fmt.Sprintf("查看%s的数据", tableName),
				"intent":      "select_all",
				"tableName":   tableName,
				"sqlTemplate": fmt.Sprintf("SELECT * FROM %s LIMIT 100", tableName),
			},
		)

		// 为数值列生成查询模式
		columnsRaw, _ := structure[tableName].([]interface{})
		for _, colRaw := range columnsRaw {
			col, ok := colRaw.(map[string]interface{})
			if !ok {
				continue
			}

			fieldName, _ := col["field"].(string)
			dataType, _ := col["type"].(string)

			if s.isNumericType(dataType) {
				queries = append(queries,
					map[string]interface{}{
						"pattern":     fmt.Sprintf("%s 的%s总和", tableName, fieldName),
						"intent":      "sum",
						"tableName":   tableName,
						"columnName":  fieldName,
						"sqlTemplate": fmt.Sprintf("SELECT SUM(%s) FROM %s", fieldName, tableName),
					},
					map[string]interface{}{
						"pattern":     fmt.Sprintf("%s 的%s平均值", tableName, fieldName),
						"intent":      "avg",
						"tableName":   tableName,
						"columnName":  fieldName,
						"sqlTemplate": fmt.Sprintf("SELECT AVG(%s) FROM %s", fieldName, tableName),
					},
				)
			}
		}
	}

	return queries
}

// 辅助函数
func (s *SemanticModelService) isNumericType(dataType string) bool {
	numericTypes := []string{"int", "integer", "bigint", "smallint", "tinyint", "float", "double", "decimal", "numeric", "real"}
	dataTypeLower := strings.ToLower(dataType)
	for _, t := range numericTypes {
		if strings.Contains(dataTypeLower, t) {
			return true
		}
	}
	return false
}

func (s *SemanticModelService) isTimeType(dataType string) bool {
	timeTypes := []string{"date", "time", "timestamp", "datetime"}
	dataTypeLower := strings.ToLower(dataType)
	for _, t := range timeTypes {
		if strings.Contains(dataTypeLower, t) {
			return true
		}
	}
	return false
}

func (s *SemanticModelService) isCategoricalType(dataType string) bool {
	catTypes := []string{"varchar", "char", "text", "string", "enum"}
	dataTypeLower := strings.ToLower(dataType)
	for _, t := range catTypes {
		if strings.Contains(dataTypeLower, t) {
			return true
		}
	}
	return false
}

// GetSemanticCache 获取语义缓存
func (s *SemanticModelService) GetSemanticCache(tenantID, dataSourceID string) (*model.SemanticModelCache, error) {
	var cache model.SemanticModelCache
	err := s.db.Where("tenant_id = ? AND data_source_id = ?", tenantID, dataSourceID).
		First(&cache).Error
	if err != nil {
		return nil, err
	}
	return &cache, nil
}

// GetSemanticContext 获取用于 AI 对话的语义上下文
func (s *SemanticModelService) GetSemanticContext(tenantID, dataSourceID string) (string, error) {
	cache, err := s.GetSemanticCache(tenantID, dataSourceID)
	if err != nil {
		return "", err
	}

	var ctx strings.Builder
	ctx.WriteString("## 语义模型上下文\n\n")

	// 解析指标
	var metrics []map[string]interface{}
	if err := json.Unmarshal([]byte(cache.Metrics), &metrics); err == nil {
		ctx.WriteString("### 可用指标\n")
		for _, m := range metrics {
			ctx.WriteString(fmt.Sprintf("- **%s** (%s): %s\n", m["name"], m["aggregation"], m["description"]))
		}
		ctx.WriteString("\n")
	}

	// 解析维度
	var dimensions []map[string]interface{}
	if err := json.Unmarshal([]byte(cache.Dimensions), &dimensions); err == nil {
		ctx.WriteString("### 可用维度\n")
		for _, d := range dimensions {
			ctx.WriteString(fmt.Sprintf("- **%s** (%s): %s\n", d["name"], d["dataType"], d["description"]))
		}
		ctx.WriteString("\n")
	}

	// 解析表关系
	var relations []map[string]interface{}
	if err := json.Unmarshal([]byte(cache.Relations), &relations); err == nil {
		ctx.WriteString("### 表关系\n")
		for _, r := range relations {
			ctx.WriteString(fmt.Sprintf("- %s.%s → %s.%s (%s)\n", r["fromTable"], r["fromColumn"], r["toTable"], r["toColumn"], r["type"]))
		}
		ctx.WriteString("\n")
	}

	return ctx.String(), nil
}

// NL2SQL 将自然语言转换为 SQL（简化版本，实际应使用 AI）
func (s *SemanticModelService) NL2SQL(tenantID, dataSourceID, nlQuery string) (string, error) {
	cache, err := s.GetSemanticCache(tenantID, dataSourceID)
	if err != nil {
		return "", err
	}

	// 解析查询模式
	var nlQueries []map[string]interface{}
	if err := json.Unmarshal([]byte(cache.NLQueries), &nlQueries); err != nil {
		return "", err
	}

	// 简单匹配（实际应使用 AI 语义理解）
	for _, q := range nlQueries {
		pattern, _ := q["pattern"].(string)
		if strings.Contains(nlQuery, strings.Split(pattern, " ")[0]) {
			if sqlTemplate, ok := q["sqlTemplate"].(string); ok {
				return sqlTemplate, nil
			}
		}
	}

	return "", fmt.Errorf("未匹配的查询模式")
}

// RefreshSemanticCache 刷新语义缓存
func (s *SemanticModelService) RefreshSemanticCache(tenantID, dataSourceID string) error {
	// 删除现有缓存
	err := s.db.Where("tenant_id = ? AND data_source_id = ?", tenantID, dataSourceID).
		Delete(&model.SemanticModelCache{}).Error
	if err != nil {
		return err
	}

	// 重新构建
	return s.BuildSemanticCache(tenantID, dataSourceID)
}
